# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Tasks for the Task runner:
#
# https://taskfile.dev

version: "3"

silent: true

vars:
  CONTAINER_EXE: podman
  JOPLIN_BACKUPS_DIR: backups/joplin-backups

tasks:
  default:
    cmds:
      - task: list

  setup:
    desc: Set up working tools
    cmds:
      - task: add-pipx
      - task: add-pip-tools
      - task: add-pre-commit
 
  add-pip-tools:
    desc: Install pip-tools
    cmds:
      - pipx --quiet install pip-tools

  add-pipx:
    desc: Install pipx
    cmds:
      - python3 -m pip install --user pipx
      - python3 -m pipx ensurepath

  add-pre-commit:
    desc: Install pre-commit
    cmds:
      - pipx --quiet install pre-commit

  backup-joplin:
    desc: Backup Joplin
    cmds:
      - mkdir -p "{{.JOPLIN_BACKUPS_PATH}}"
      - zip -r "{{.JOPLIN_BACKUPS_PATH}}/joplin-backup-{{.BACKUP_TIMESTAMP}}.zip" "{{.CONFIG_DIR}}/joplin-desktop"
    vars:
      BACKUP_TIMESTAMP:
        sh: date -u +"%Y-%m-%dT%H-%M-%SZ"
      JOPLIN_BACKUPS_PATH: "{{.HOME}}/{{.JOPLIN_BACKUPS_DIR}}"
      CONFIG_DIR: "{{.HOME}}/.config"

  clean-oci:
    desc: Remove obsolete containers and images
    cmds:
      - "{{.CONTAINER_EXE}} system prune -f"

  list:
    desc: List available tasks
    cmds:
      - task --list

  rm-pip-tools:
    desc: Remove pip-tools
    cmds:
      - pipx --quiet uninstall pip-tools

  rm-pipx:
    desc: Remove pipx
    cmds:
      - pipx uninstall-all
      - python3 -m pip uninstall -qy pipx

  rm-pre-commit:
    desc: Remove pre-commit
    cmds:
      - pipx --quiet uninstall pre-commit

  system-info:
    desc: Display system information
    cmds:
      - "echo CPU architecture: {{ARCH}}"
      - "echo Operating system: {{OS}}"
