# Package repositories
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Homebrew Packages
brew "awscli"
brew "git"
brew "hugo"
brew "node@14"
brew "packer"
brew "rclone"
brew "shellcheck"
brew "terraform"

# Cask packages
cask "anki"
cask "docker"
cask "firefox"
cask "joplin"
cask "libreoffice"
cask "postman"
cask "raspberry-pi-imager"
cask "skype"
cask "signal"
cask "slack"
cask "vscodium"
cask "zoom"
